<a href="https://colab.research.google.com/github/seth-huffman/School-Projects/blob/main/01_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notebook #1: Python, Pandas, and Pokemon!

**Due Wednesday, September 9th, 2026 by 11:59pm**

The goal of this notebook is to become comfortable with using `python` and `pandas` as well as grabbing specific slices of the dataset.

Start off by importing the data as we did in `practice-assignment`. Make sure the data is in your Google Drive, and that you update the path to point to where you have your data saved in Drive.

In [2]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
#import the data:

#make sure the path on the line below corresponds to the path where you put your dataset.
#for example, I usually put my input files on 'datasets' directory as shown below
poke = pd.read_csv('/content/drive/MyDrive/cs167_fall26/datasets/pokemon.csv')
poke.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

## Exercise #1:
Print out all of the unique possible values for the `Type 1` column of the dataset.
- *Hint: I'm looking for each possible primary type to be ouput once, not a list of primary type of each pokemon. For example, if I tossed a coin 3 times and got Heads, Tails, Heads, the possible values of the coin flip are Heads and Tails. There is a function for this.*

In [4]:
from enum import unique
typeOne = poke['Type 1']
typeOne.unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

## Exercise #2:
Create a subset of data representing pokemon whose primary type is **Fire** 🔥 , and the second type is **Flying** 🦅. Save this DataFrame to the variable name `fire_flying_pokemon`. Display the first 5 lines of this subset.

In [5]:
typeOne = poke['Type 1']
typeTwo = poke['Type 2']
fire_flying_pokemon = poke[(typeOne == 'Fire') & (typeTwo == 'Flying')]
fire_flying_pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
158,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
270,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
730,662,Fletchinder,Fire,Flying,382,62,73,55,56,52,84,6,False

## Exercise #3
Using `fire_flying_pokemon`, what is the median **Attack** of Fire Flying Pokemon?

In [13]:
attack = fire_flying_pokemon['Attack'].median()
attack

92.0

## Exercise #4
Create a subset with only pokemon from Generation I. Include 5 columns, the `Generation`, `Name`, `Type 1`, `Type 2`, and `Total`.
  - *For an extra challenge, see if you can do this in one line.*

In [14]:
subset = poke[ ['Generation', 'Name', 'Type 1', 'Type 2', 'Total'] ]
subset

     Generation                   Name   Type 1  Type 2  Total
0             1              Bulbasaur    Grass  Poison    318
1             1                Ivysaur    Grass  Poison    405
2             1               Venusaur    Grass  Poison    525
3             1  VenusaurMega Venusaur    Grass  Poison    625
4             1             Charmander     Fire     NaN    309
..          ...                    ...      ...     ...    ...
795           6                Diancie     Rock   Fairy    600
796           6    DiancieMega Diancie     Rock   Fairy    700
797           6    HoopaHoopa Confined  Psychic   Ghost    600
798           6     HoopaHoopa Unbound  Psychic    Dark    680
799           6              Volcanion     Fire   Water    600

[800 rows x 5 columns]

## Exercise #5

Which primary type of pokemon is the overall strongest? (not looking for philsophical debates here, I'm looking at the average of the 'Total' column, grouped by Type-1 -  Fire v Water v Grass etc.).
- *Hint: Don't forget to actually answer the question here...*

In [15]:
strongest = poke.groupby('Type 1')['Total'].mean()
sorted = strongest.sort_values(ascending=False)
sorted
# Dragon

Type 1
Dragon      550.531250
Steel       487.703704
Flying      485.000000
Psychic     475.947368
Fire        458.076923
Rock        453.750000
Dark        445.741935
Electric    443.409091
Ghost       439.562500
Ground      437.500000
Ice         433.458333
Water       430.455357
Grass       421.142857
Fighting    416.444444
Fairy       413.176471
Normal      401.683673
Poison      399.142857
Bug         378.927536
Name: Total, dtype: float64

## Exercise #6
**Do something cool**. Using the Pokemon dataset, get creative and show me something about the dataset. Use a text cell to explain what you did.
 - *Need some help gettting started here? Try asking a question about the dataset and see if you can use Python and Pandas to answer the question*

In [16]:
sorted.describe()

count     18.000000
mean     442.869683
std       39.749064
min      378.927536
25%      417.619048
50%      438.531250
75%      456.995192
max      550.531250
Name: Total, dtype: float64